#!/usr/bin/env python3
"""
Generate KiCad PCB file for TurboQuant V5
4-layer, 100×80mm with component placement
"""

def generate_pcb():
    lines = []
    
    # Header
    lines.extend([
        "(kicad_pcb",
        "  (version 20221018)",
        "  (generator \"pcbnew\")",
        "  (generator_version \"7.0\")",
        "",
        "  (general",
        "    (thickness 1.6)",
        "    (legacy_teardrops no)",
        "  )",
        "",
        "  (paper \"A4\")",
        "  (title_block",
        '    (title "TurboQuant Mux LNA Board v5.0")',
        '    (date "2026-04-26")',
        '    (rev "5.0")',
        '    (company "TurboQuant")',
        "  )",
        "",
        "  (layers",
        '    (0 "F.Cu" signal)',
        '    (1 "In1.Cu" signal)',
        '    (2 "In2.Cu" signal)',
        '    (31 "B.Cu" signal)',
        '    (32 "B.Adhes" user "B.Adhesive")',
        '    (33 "F.Adhes" user "F.Adhesive")',
        '    (34 "B.Paste" user)',
        '    (35 "F.Paste" user)',
        '    (36 "B.SilkS" user "B.Silkscreen")',
        '    (37 "F.SilkS" user "F.Silkscreen")',
        '    (38 "B.Mask" user)',
        '    (39 "F.Mask" user)',
        '    (40 "Dwgs.User" user "User.Drawings")',
        '    (41 "Cmts.User" user "User.Comments")',
        '    (42 "Eco1.User" user "User.Eco1")',
        '    (43 "Eco2.User" user "User.Eco2")',
        '    (44 "Edge.Cuts" user)',
        '    (45 "Margin" user)',
        '    (46 "B.CrtYd" user "B.Courtyard")',
        '    (47 "F.CrtYd" user "F.Courtyard")',
        '    (48 "B.Fab" user "B.Fabrication")',
        '    (49 "F.Fab" user "F.Fabrication")',
        "  )",
        "",
        "  (setup",
        '    (pad_to_mask_clearance 0)',
        '    (pcbplotparams',
        '      (layerselection 0x00010fc_ffffffff)',
        '      (plot_on_all_layers_selection 0x0000000_00000000)',
        '      (disableapertmacros no)',
        '      (usegerberextensions no)',
        '      (usegerberattributes yes)',
        '      (usegerberadvancedattributes yes)',
        '      (creategerberjobfile yes)',
        '      (dashed_line_dash_ratio 12.000000)',
        '      (dashed_line_gap_ratio 3.000000)',
        '      (svgprecision 4)',
        '      (plotframeref no)',
        '      (viasonmask no)',
        '      (mode 1)',
        '      (useauxorigin no)',
        '      (hpglpennumber 1)',
        '      (hpglpenspeed 20)',
        '      (hpglpendiameter 15.000000)',
        '      (pdf_front_fp_property_popups yes)',
        '      (pdf_back_fp_property_popups yes)',
        '      (dxfpolygonmode yes)',
        '      (dxfimperialunits yes)',
        '      (dxfusepcbnewfont yes)',
        '      (psnegative no)',
        '      (psa4output no)',
        '      (plotreference yes)',
        '      (plotvalue yes)',
        '      (plotfptext yes)',
        '      (plotinvisibletext no)',
        '      (sketchpadsonfab no)',
        '      (subtractmaskfromsilk no)',
        '      (outputformat 1)',
        '      (mirror no)',
        '      (drillshape 1)',
        '      (scaleselection 1)',
        '      (outputdirectory "")',
        "    )",
        "  )",
        "",
    ])
    
    # Net classes
    lines.extend([
        "  (net 0 \"\")",
        '  (net 1 "+12V")',
        '  (net 2 "+5V")',
        '  (net 3 "+3V3")',
        '  (net 4 "GND")',
        '  (net 5 "TX_BUS")',
        '  (net 6 "RX0_OUT")',
        '  (net 7 "RX1_OUT")',
        '  (net 8 "MUX_A")',
        '  (net 9 "MUX_B")',
        '  (net 10 "MUX_C")',
        '  (net 11 "MUX_EN")',
        '  (net 12 "GATE0")',
        '  (net 13 "GATE1")',
        '  (net 14 "GATE2")',
        '  (net 15 "GATE3")',
        '  (net 16 "GATE4")',
        '  (net 17 "GATE5")',
        '  (net 18 "GATE6")',
        '  (net 19 "GATE7")',
        "",
        "  (net_class Default \"This is the default net class.\"",
        "    (clearance 0.2)",
        "    (trace_width 0.25)",
        "    (via_dia 0.8)",
        "    (via_drill 0.4)",
        "    (uvia_dia 0.3)",
        "    (uvia_drill 0.1)",
        "    (add_net \"\")",
        '    (add_net "+12V")',
        '    (add_net "+5V")',
        '    (add_net "+3V3")',
        '    (add_net "GND")',
        '    (add_net "TX_BUS")',
        '    (add_net "RX0_OUT")',
        '    (add_net "RX1_OUT")',
        '    (add_net "MUX_A")',
        '    (add_net "MUX_B")',
        '    (add_net "MUX_C")',
        '    (add_net "MUX_EN")',
        '    (add_net "GATE0")',
        '    (add_net "GATE1")',
        '    (add_net "GATE2")',
        '    (add_net "GATE3")',
        '    (add_net "GATE4")',
        '    (add_net "GATE5")',
        '    (add_net "GATE6")',
        '    (add_net "GATE7")',
        "  )",
        "",
        '  (net_class HV "High voltage TX traces"',
        "    (clearance 2.0)",
        "    (trace_width 1.0)",
        "    (via_dia 1.2)",
        "    (via_drill 0.6)",
        '    (add_net "TX_BUS")',
        "  )",
        "",
    ])
    
    # Board edge
    lines.extend([
        "  (gr_rect (start 0 0) (end 100 80) (layer \"Edge.Cuts\") (width 0.1))",
        "",
    ])
    
    # Zone definitions
    lines.extend([
        "  ; === GND PLANE (In1.Cu) ===",
        '  (zone (net 4) (net_name "GND") (layer "In1.Cu") (tstamp 0) (hatch edge 0.508)',
        '    (connect_pads (clearance 0.2))',
        '    (min_thickness 0.254)',
        '    (filled_areas_thickness no)',
        '    (fill yes (thermal_gap 0.508) (thermal_bridge_width 0.508))',
        '    (polygon',
        '      (pts',
        '        (xy 0 0)',
        '        (xy 100 0)',
        '        (xy 100 80)',
        '        (xy 0 80)',
        "      )",
        "    )",
        "  )",
        "",
        "  ; === +5V PLANE (In2.Cu) ===",
        '  (zone (net 2) (net_name "+5V") (layer "In2.Cu") (tstamp 1) (hatch edge 0.508)',
        '    (connect_pads (clearance 0.2))',
        '    (min_thickness 0.254)',
        '    (filled_areas_thickness no)',
        '    (fill yes (thermal_gap 0.508) (thermal_bridge_width 0.508))',
        '    (polygon',
        '      (pts',
        '        (xy 0 0)',
        '        (xy 50 0)',
        '        (xy 50 80)',
        '        (xy 0 80)',
        "      )",
        "    )",
        "  )",
        "",
        "  ; === +12V PLANE (In2.Cu, TX zone) ===",
        '  (zone (net 1) (net_name "+12V") (layer "In2.Cu") (tstamp 2) (hatch edge 0.508)',
        '    (connect_pads (clearance 0.2))',
        '    (min_thickness 0.254)',
        '    (filled_areas_thickness no)',
        '    (fill yes (thermal_gap 0.508) (thermal_bridge_width 0.508))',
        '    (polygon',
        '      (pts',
        '        (xy 50 40)',
        '        (xy 100 40)',
        '        (xy 100 80)',
        '        (xy 50 80)',
        "      )",
        "    )",
        "  )",
        "",
    ])
    
    # Component placements
    # Power zone components
    lines.extend([
        "  ; === POWER ZONE COMPONENTS ===",
        "",
        "  ; 12V input terminal",
        '  (footprint "Connector_TerminalBlock:TerminalBlock_bornier-2_P5.08mm"',
        '    (layer "F.Cu")',
        '    (at 10 20 0)',
        '    (descr "2-pin screw terminal")',
        '    (tags "screw terminal")',
        '    (property "Reference" "J1" (at 0 -3.5 0) (layer "F.SilkS"))',
        '    (property "Value" "12V_Input" (at 0 3.5 0) (layer "F.Fab"))',
        '    (pad "1" thru_hole circle (at -2.54 0) (size 2.5 2.5) (drill 1.2) (layers "*.Cu" "*.Mask") (net 1))',
        '    (pad "2" thru_hole circle (at 2.54 0) (size 2.5 2.5) (drill 1.2) (layers "*.Cu" "*.Mask") (net 4))',
        "  )",
        "",
        "  ; Polyfuse",
        '  (footprint "Fuse:Fuse_1206_3216Metric"',
        '    (layer "F.Cu")',
        '    (at 15 20 90)',
        '    (property "Reference" "F1" (at 0 -2 0) (layer "F.SilkS"))',
        '    (property "Value" "2A" (at 0 2 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at -1.5 0) (size 1.2 1.8) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 1))',
        '    (pad "2" smd roundrect (at 1.5 0) (size 1.2 1.8) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 1))',
        "  )",
        "",
        "  ; LM7805 DPAK",
        '  (footprint "Package_TO_SOT_SMD:TO-252-2"',
        '    (layer "F.Cu")',
        '    (at 15 32 0)',
        '    (property "Reference" "U1" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "LM7805" (at 0 4 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at -2.3 2.2) (size 1.2 1.5) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 1))',
        '    (pad "2" smd roundrect (at 0 -2.2) (size 2.5 3.2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 4))',
        '    (pad "3" smd roundrect (at 2.3 2.2) (size 1.2 1.5) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 2))',
        "  )",
        "",
        "  ; AMS1117-3.3 SOT-223",
        '  (footprint "Package_TO_SOT_SMD:SOT-223-3_TabPin2"',
        '    (layer "F.Cu")',
        '    (at 22 32 0)',
        '    (property "Reference" "U2" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "AMS1117-3.3" (at 0 4 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at -2.3 2.8) (size 1.2 1.8) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 4))',
        '    (pad "2" smd roundrect (at 0 -2.8) (size 3.6 2.2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 3))',
        '    (pad "3" smd roundrect (at 2.3 2.8) (size 1.2 1.8) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 2))',
        "  )",
        "",
    ])
    
    # Digital zone components
    lines.extend([
        "  ; === DIGITAL ZONE COMPONENTS ===",
        "",
        "  ; E1 GPIO connector",
        '  (footprint "Connector_PinHeader_2.54mm:PinHeader_2x10_P2.54mm_Vertical"',
        '    (layer "F.Cu")',
        '    (at 42 20 0)',
        '    (property "Reference" "J3" (at 0 -8 0) (layer "F.SilkS"))',
        '    (property "Value" "E1_GPIO" (at 0 8 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; 74HCT595",
        '  (footprint "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 35 28 0)',
        '    (property "Reference" "U5" (at 0 -6 0) (layer "F.SilkS"))',
        '    (property "Value" "74HCT595" (at 0 6 0) (layer "F.Fab"))',
        "  )",
        "",
    ])
    
    # Analog zone components
    lines.extend([
        "  ; === ANALOG ZONE COMPONENTS ===",
        "",
        "  ; DG408 MUX0",
        '  (footprint "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 15 55 0)',
        '    (property "Reference" "U3" (at 0 -6 0) (layer "F.SilkS"))',
        '    (property "Value" "DG408" (at 0 6 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; DG408 MUX1",
        '  (footprint "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 15 65 0)',
        '    (property "Reference" "U4" (at 0 -6 0) (layer "F.SilkS"))',
        '    (property "Value" "DG408" (at 0 6 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; OPA1641 LNA0",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 35 55 0)',
        '    (property "Reference" "U6" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "OPA1641" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; OPA1641 LNA1",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 35 65 0)',
        '    (property "Reference" "U7" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "OPA1641" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
    ])
    
    # TX Switch zone components
    lines.extend([
        "  ; === TX SWITCH ZONE COMPONENTS ===",
        "",
        "  ; TC4427 Gate Driver 0-1",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 58 50 0)',
        '    (property "Reference" "U8" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "TC4427" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; TC4427 Gate Driver 2-3",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 58 58 0)',
        '    (property "Reference" "U9" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "TC4427" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; TC4427 Gate Driver 4-5",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 58 66 0)',
        '    (property "Reference" "U10" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "TC4427" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
        "  ; TC4427 Gate Driver 6-7",
        '  (footprint "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"',
        '    (layer "F.Cu")',
        '    (at 58 74 0)',
        '    (property "Reference" "U11" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "TC4427" (at 0 4 0) (layer "F.Fab"))',
        "  )",
        "",
    ])
    
    # IRF830 MOSFETs (placed in a row for heatsink)
    for i in range(8):
        x_pos = 72 + (i % 4) * 8
        y_pos = 48 if i < 4 else 68
        lines.extend([
            f"  ; IRF830 CH{i}",
            f'  (footprint "Package_TO_SOT_THT:TO-220-3_Vertical"',
            f'    (layer "F.Cu")',
            f'    (at {x_pos} {y_pos} 0)',
            f'    (property "Reference" "Q{i+9}" (at 0 -5 0) (layer "F.SilkS"))',
            f'    (property "Value" "IRF830" (at 0 5 0) (layer "F.Fab"))',
            f'    (pad "1" thru_hole circle (at -2.54 0) (size 2 2) (drill 1.2) (layers "*.Cu" "*.Mask"))',
            f'    (pad "2" thru_hole circle (at 0 0) (size 2 2) (drill 1.2) (layers "*.Cu" "*.Mask"))',
            f'    (pad "3" thru_hole circle (at 2.54 0) (size 2 2) (drill 1.2) (layers "*.Cu" "*.Mask"))',
            "  )",
            "",
        ])
    
    # TX_BUS output connector
    lines.extend([
        "  ; TX_BUS SMA connector",
        '  (footprint "Connector_Coaxial:SMA_EDGE"',
        '    (layer "F.Cu")',
        '    (at 95 60 0)',
        '    (property "Reference" "J2" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "TX_BUS" (at 0 4 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at 0 0) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 5))',
        '    (pad "2" smd roundrect (at 0 -2.5) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 4))',
        "  )",
        "",
    ])
    
    # RX outputs
    lines.extend([
        "  ; RX0_OUT SMA connector",
        '  (footprint "Connector_Coaxial:SMA_EDGE"',
        '    (layer "F.Cu")',
        '    (at 95 50 0)',
        '    (property "Reference" "J4" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "RX0_OUT" (at 0 4 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at 0 0) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 6))',
        '    (pad "2" smd roundrect (at 0 -2.5) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 4))',
        "  )",
        "",
        "  ; RX1_OUT SMA connector",
        '  (footprint "Connector_Coaxial:SMA_EDGE"',
        '    (layer "F.Cu")',
        '    (at 95 70 0)',
        '    (property "Reference" "J5" (at 0 -4 0) (layer "F.SilkS"))',
        '    (property "Value" "RX1_OUT" (at 0 4 0) (layer "F.Fab"))',
        '    (pad "1" smd roundrect (at 0 0) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 7))',
        '    (pad "2" smd roundrect (at 0 -2.5) (size 2 2) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net 4))',
        "  )",
        "",
    ])
    
    # Footer
    lines.extend([
        ")",
    ])
    
    return "\n".join(lines)

if __name__ == "__main__":
    pcb = generate_pcb()
    with open("/home/james/.openclaw/workspace/turboquant_v5/hardware/schematics/turboquant_mux_lna_v5.kicad_pcb", "w") as f:
        f.write(pcb)
    print(f"Generated PCB file ({len(pcb)} bytes)")
